app/main/routes.py
from app.models import User, Pitch, Otp
from flask import render_template, url_for, Blueprint

main= Blueprint('main',__name__)

@main.route('/')
def home():
    # All pitches here
    pitches = Pitch.query.all()

    # comments_list = comments_cutter(pitches.comments)
    return render_template('index.html', pitches=pitches)

app/pitch/routes.py
from flask import Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app.pitch.forms import PitchForm,CommentsForm
from app.models import Pitch
from app import db
from flask import render_template, url_for, flash, redirect, request


posts= Blueprint('posts',__name__)


@posts.route('/comments/<id>',methods=['POST', 'GET'])
@login_required
def comments(id):
    form = CommentsForm()
    pitch = Pitch.query.filter_by(id=id).first()
    if form.validate_on_submit():
        pitch.comments+=form.content.data + '~'
        db.session.commit()
        flash('Your comment was added successfully')
        
        return redirect(url_for('main.home'))
    form.content.data = "Your comment here"
    return render_template('comments.html', form=form , pitch=pitch)





@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(title=form.title.data,
                      content=form.content.data, user_id=current_user.id,category=form.category.data)
        db.session.add(pitch)
        db.session.commit()
        flash('Your pitch was successfully added')
        return redirect(url_for('main.home'))
    return render_template('create.html', form=form, title='New Pitch')


@posts.route('/post/like/<int:pitchid>', methods=['GET'])
@login_required
def likes(pitchid):
    """
    Adds a like when click of a button

    Returns:
        _type_: _description_
    """

    pitch = Pitch.query.filter_by(id=pitchid).first()

    # update = pitch.likes + 1
    pitch.likes += 1
    # pitch.dislikes -= 1
    db.session.commit()
    # return str(pitch.likes)
    return redirect(url_for('main.home'))


@posts.route('/post/dislikes/<int:pitchid>', methods=['POST', 'GET'])
@login_required
def dislikes(pitchid):
    """
    Adds a dislikes when click of a button

    Returns:
        _type_: _description_
    """

    pitch = Pitch.query.filter_by(id=pitchid).first()

    pitch.dislikes += 1
    # pitch.likes -= 1
    db.session.commit()
    return redirect(url_for('main.home'))

@posts.route('/categories/<category>')
def categories(category):
    pitches = Pitch.query.filter_by(category=category)
    return render_template('categories.html', pitches=pitches)

@login_required
@posts.route('/post/edit/<postid>',methods=['POST', 'GET'])
def post_edit(postid):
    form = PitchForm()

    edites= Pitch.query.filter_by(id=postid).first()
    
    if form.validate_on_submit():
        edites.title = form.title.data
        edites.content=form.content.data
        edites.category=form.category.data
        
        db.session.add(edites)
        db.session.commit()
        flash('Your Pitch Has been updated!','success')
        return redirect(url_for("main.home"))
    else:
        form.title.data=edites.title
        form.content.data=edites.content
        form.category.data=edites.category
        
    return render_template('post_edit.html',form=form)

@posts.route('/post/delete/<pitchid>')
def post_delete(pitchid):
    pitch = Pitch.query.filter_by(id=pitchid).first()
    db.session.delete(pitch)
    db.session.commit()
    return redirect(url_for('main.home'))

app/users/routes.py
from flask import Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask import render_template, url_for, flash, redirect, request
from app.users.forms import Register, Login,ResetPassword,UpdateAccountForm,VerifyOtp,ForgotPassword
from app import  db, bcrypt,mail
from flask_mail import  Message
import random
import math
from app.models import Pitch
from app.users.utils import save_picture

from app.models import User, Otp


users= Blueprint('users',__name__)

@users.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Register()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your Account Has been Created! You are now able to login  in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/authentification/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Login()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Welcome {user.username.title()} !! ', 'success')
            # args is a dict
            # get returns none if the next key does not exist
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account',methods=['POST', 'GET'])
@login_required
def account():
    """
    """
    
    pitch= Pitch.query.filter_by(user_id=current_user.id)
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture=save_picture(form.picture.data)
            current_user.profile=picture
             
        current_user.username=form.username.data
        current_user.email=form.email.data

        db.session.commit()
        flash('Your Account Has been updated!','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':

        form.username.data=current_user.username
        form.email.data=current_user.email
    
    # msg=Message("Hello",sender="apollolibrary99@gmail.com",recipients=['abduba13@gmail.com'])
    # msg.body = "Rich JAFFARRRRRRRR"
    # mail.send(msg)
    image_file= url_for('static',filename='profiles/'+current_user.profile)
    return render_template('account.html', title='Account',image_file=image_file,form=form,pitch=pitch )

@users.route('/forgot/password',methods=['POST','GET'])
def forgot_password():
    form=ForgotPassword()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        token=generate_token(6)
        otp=Otp(otp=token,user_id=user.id)
        db.session.add(otp)
        db.session.commit()
        if user:    
            msg=Message("Hello",sender="apollolibrary99@gmail.com",recipients=[user.email])
            msg.body = token
            mail.send(msg)
            flash('We have sent you an email with instructions to reset your password')
            return redirect(url_for('users.verify_otp',userid=user.id))

    return render_template('forgot_password.html',form=form)

@users.route('/otp-verify/<userid>',methods=['POST', 'GET'])
def verify_otp(userid):
    form = VerifyOtp()
    user=User.query.filter_by(id=userid).first()
    token=Otp.query.filter_by(user_id=userid).first()
    
    if form.validate_on_submit():

        if form.otp.data != token.otp:
            flash('InCorrect otp')
        else:
            flash('Correct otp')
            u=db.session.get(Otp,1)
            db.session.delete(u)
            db.session.commit()
            return redirect(url_for('users.reset',userid=user.id))

    return render_template('otp_verification.html',form=form)


def generate_token(length):
    digits = [i for i in range(0, 10)]

    token=""
    for i in range(length):
        index=math.floor(random.random()*10)
        token+=str(digits[index])
    return token

@users.route('/reset_password/<userid>',methods=['POST','GET'])
def reset(userid):
    form=ResetPassword()
    user=User.query.filter_by(id=userid).first()

    if form.validate_on_submit():
        if user.password != form.password.data:
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.home'))
        else:
            flash('Old and new password cannot be the same')
    return render_template('reset_password.html',form=form)

app/templates/account.html
{% extends 'layout.html' %}
{% block body %}
{% from 'bootstrap5/form.html' import render_form %}
<div class="container">
<div class="row">
    <div class="col-md-6">
        <div class="container-fluid row p-5">
            <div class="col-md-4">
                <img src="{{image_file}}"  class="img-thumbnail img-fluid border border-white" alt="Profile picture" >
            </div>
            <div class="col-md-8 mx-auto mt-auto mb-auto  lead">
                <p>Username--: {{ current_user.username.title() }}</p>
                
                <p>Email-------: {{ current_user.email }}</p>
               
                <a data-bs-toggle="collapse" href="#coll" class="text-decoration-none text-muted" >Update Info</a>
    
            </div>
        </div>
        <div class="container-fluid collapse" id="coll">
            {{render_form(form)}}
        </div>
    </div>
    <div class="col-md-6">
        <p class="display-6 text-center">
            My Posts
        </p>
        <div class="container-fluid d-flex flex-wrap flex-row justify-content-center">
            {% for pitch in pitch %}
                <div class=" pitches card  m-4">
                  
                      <div class="row  p-2">
                          <div class="col-md-7 mx-auto mt-auto mb-auto">
                            {% if current_user.id == pitch.author.id %}
                            <div class="d-inline mx-3">
                              <a href="{{url_for('posts.post_delete',pitchid=pitch.id)}}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                              </svg></a>
                            <a href="{{url_for('posts.post_edit',postid=pitch.id)}}"> <svg  xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                              </svg>
                            </a> 
                             </div>
                            {% endif %}
                          
                           <p class="d-inline">{{pitch.category}}</p>
                          </div>
                        <div class="col-md-2">
                            <img src="{{url_for('static', filename='/profiles/'+pitch.author.profile)}}" class="img-thumbnail img-fluid border border-white" alt="Profile picture" >
                        </div>
                        <div class="col-md-3 mx-auto mt-auto mb-auto text-muted">
                            <small>{{pitch.author.username}}</small>
                            <br>
                            <small>{{pitch.date_created}}</small>
                        </div>
                      </div>
                    <div class="card-body">
                      <h5 class="card-title">{{pitch.title}}</h5>
                      <p class="card-text lead">{{pitch.content}}</p>
                      <div class="d-flex justify-content-around">
                        <a href="{{url_for('posts.likes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/like.svg')}}" alt=""></a>{{pitch.likes}}
                        <a href="{{url_for('posts.dislikes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/unlike.svg')}}"  alt=""></a>{{pitch.dislikes}}
                        <a  data-bs-toggle="collapse" href="#comments{{pitch.id}}" class="lead text-decoration-none">
                          <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
                        </a>
                      </div>
                      <div class="collapse" id="comments{{pitch.id}}">
                    {% if pitch.comments %}
                    <div class=" comments my-3">
                      <p>Comments</p>
                      {% for comment in  pitch.comments.split('~') %}
                        <div class="card m-1">
                          <p class="lead">
                            {{comment}}
                          </p>
                        </div>
                      {% endfor %}
                    </div>
                    {% endif %}
                  <a href="{{url_for('posts.comments',id=pitch.id)}}">ADD</a>
                        </div>
                      </div>
                    
                  </div>
                
              {% endfor %}
               
        </div>
</div>


</div>
</div>
{%endblock%}

app/templates/categories.html
{% extends 'layout.html' %}
{% block body %}
<div class="container-fluid d-flex flex-wrap flex-row justify-content-center">
    {% for pitch in pitches %}
        <div class="pitches card my-2 mx-4">
          
              <div class="row  p-2">
                  <div class="col-md-7 mx-auto mt-auto mb-auto">
                    {% if current_user.id == pitch.author.id %}
                    <div class="d-inline mx-3">
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                      </svg>
                      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                     </div>
                    {% endif %}
                  
                   <p class="d-inline">{{pitch.category}}</p>
                  </div>
                <div class="col-md-2">
                    <img src="{{url_for('static', filename='/profiles/'+pitch.author.profile)}}" class="img-thumbnail img-fluid border border-white" alt="Profile picture" >
                </div>
                <div class="col-md-3 mx-auto mt-auto mb-auto text-muted">
                    <small>{{pitch.author.username}}</small>
                    <br>
                    <small>{{pitch.date_created}}</small>
                </div>
              </div>
            <div class="card-body">
              <h5 class="card-title">{{pitch.title}}</h5>
              <p class="card-text lead">{{pitch.content}}</p>
              <div class="d-flex justify-content-around">
                <a href="{{url_for('posts.likes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/like.svg')}}" alt=""></a>{{pitch.likes}}
                <a href="{{url_for('posts.dislikes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/unlike.svg')}}"  alt=""></a>{{pitch.dislikes}}
                <a  data-bs-toggle="collapse" href="#comments{{pitch.id}}" class="lead text-decoration-none">
                  <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
                </a>
              </div>
              <div class="collapse" id="comments{{pitch.id}}">
            {% if pitch.comments %}
            <div class=" comments my-3">
              <p>Comments</p>
              {% for comment in  pitch.comments.split('~') %}
                <div class="card m-1">
                  <p class="lead">
                    {{comment}}
                  </p>
                </div>
              {% endfor %}
            </div>
            {% endif %}
          <a href="{{url_for('posts.comments',id=pitch.id)}}">ADD</a>
                </div>
              </div>
            
          </div>
        
      {% endfor %}
       
</div>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}
{% block body %}
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-6  mx-auto mt-auto mb-auto px-5 ">
                <p class="h3">
                    Create a pitch today
                </p>
                <p class="lead">
                    Create a pitch today for any category you want and vote on pitches already made...Who knows you might find
                    something intresting browse and copy what you might like 
                </p>
                <a href="{{url_for('posts.create')}}" class="btn btn-lg btn-outline">CREATE</a>
            </div>
            <div class="col-md-6">
                <img src="{{url_for('static',filename='/assets/img.svg')}}" class="img-responsive f-img m-5" alt="">
            </div>
        </div>
    </div>
    <!-- To be removed -->
    <div class="container-fluid d-flex flex-wrap flex-row justify-content-center">
    {% for pitch in pitches %}
        <div class=" pitches card  m-4">
          
              <div class="row  p-2">
                  <div class="col-md-7 mx-auto mt-auto mb-auto">
                    {% if current_user.id == pitch.author.id %}
                    <div class="d-inline mx-3">
                      <a href="{{url_for('posts.post_delete',pitchid=pitch.id)}}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                        <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                      </svg></a>
                    <a href="{{url_for('posts.post_edit',postid=pitch.id)}}"> <svg  xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                      </svg>
                    </a> 
                     </div>
                    {% endif %}
                  
                   <p class="d-inline">{{pitch.category}}</p>
                  </div>
                <div class="col-md-2">
                    <img src="{{url_for('static', filename='/profiles/'+pitch.author.profile)}}" class="img-thumbnail img-fluid border border-white" alt="Profile picture" >
                </div>
                <div class="col-md-3 mx-auto mt-auto mb-auto text-muted">
                    <small>{{pitch.author.username}}</small>
                    <br>
                    <small>{{pitch.date_created}}</small>
                </div>
              </div>
            <div class="card-body">
              <h5 class="card-title">{{pitch.title}}</h5>
              <p class="card-text lead">{{pitch.content}}</p>
              <div class="d-flex justify-content-around">
                <a href="{{url_for('posts.likes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/like.svg')}}" alt=""></a>{{pitch.likes}}
                <a href="{{url_for('posts.dislikes',pitchid=pitch.id)}}"><img src="{{url_for('static',filename='/assets/unlike.svg')}}"  alt=""></a>{{pitch.dislikes}}
                <a  data-bs-toggle="collapse" href="#comments{{pitch.id}}" class="lead text-decoration-none">
                  <img src="{{url_for('static',filename='/assets/comment.svg')}}" height="30" alt=""> 
                </a>
              </div>
              <div class="collapse" id="comments{{pitch.id}}">
            {% if pitch.comments %}
            <div class=" comments my-3">
              <p>Comments</p>
              {% for comment in  pitch.comments.split('~') %}
                <div class="card m-1">
                  <p class="lead">
                    {{comment}}
                  </p>
                </div>
              {% endfor %}
            </div>
            {% endif %}
          <a href="{{url_for('posts.comments',id=pitch.id)}}">ADD</a>
                </div>
              </div>
            
          </div>
        
      {% endfor %}
       
</div>
     
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href='{{url_for('static',filename='main.css')}}'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
    crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
</head>
<body>
    <div class="container-fluid">
        <!-- Nav Bar------------------------------------------------ -->
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent">
              <div class="container-fluid">
                <a class="navbar-brand"  href="{{url_for('main.home')}}">
                  <img src= "{{url_for('static',filename='/assets/logo.svg')}}" alt="logo" width="75" height="45" >
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-evenly " id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" href="{{url_for('posts.categories',category='Tech')}}">Tech</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" href="{{url_for('posts.categories',category='Health')}}">Health</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" href="{{url_for('posts.categories',category='Transport')}}">Transport</a>
                    </li>
                    <li class="nav-item me-5">
                      <a class="nav-link active" href="{{url_for('posts.categories',category='Agriculture')}}">Agriculture</a>
                    

                      {% if current_user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link active me-5" href="{{url_for('posts.create')}}">Create</a>
                        </li>
                      <li class="nav-item">
                      <a class="nav-link active " href="{{url_for('users.account')}}">Account</a>
                    </li> 
                      <li class="nav-item">
                    <a class="nav-link active" href="{{url_for('users.logout')}}">Logout</a>
                      </li>
                      <li class="nav-item ">
                        <a  href="#" class="nav-link active" >
                          {{current_user.username.title()}}
                        </a>
                     </li>
                    
             
                      {%else%}
                      {%if request.url_rule.endpoint != 'register' %}
                      <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('users.register')}}">Register</a>
                      </li>
                      {% endif %}
                      {%if request.url_rule.endpoint != 'login'%}
                      <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('users.login')}}">Login</a>
                      </li>
                      {%endif%}
                      {% endif %}
                    

                </div>
              </div>
            </nav>
        </div>
        {% with messages = get_flashed_messages(with_categories = true) %} 
        {% if messages %}
        {%for category,message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show">{{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endfor%}
        {% endif %}
        {% endwith %}
        {% block body %}
            
        {% endblock %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="{{ url_for('static',filename='script.js')}}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </div>
</body>
</html>